### ISSUE TITLE
Hmm, I just found this repo

### ISSUE THREAD

**Issue by omgimanerd** [rtorr/do-cli#2]
I think it's kind of funny that I found this repo since I made [this](http://github.com/omgimanerd/docli)

**Comment by rtorr** [comment]
I will happily give you the npm name if you are interested

**Comment by omgimanerd** [comment]
Sadly I'm looking for the npm name docli without the hyphen :(
Thanks very much for the offer though.
EDIT: I might take you up on that offer if I can't get npmjs.com/package/docli
